/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
import 'vue'
declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: import("vue").DefineComponent<{
        name: {
            type: import("vue").PropType<"svg-bangbangtang" | "svg-baomihua" | "svg-bingqilin" | "svg-hanbao" | "svg-pintu" | "svg-react" | "svg-sanmingzhi" | "svg-sharp-arrow-back-ios" | "svg-sharp-check" | "svg-tabbar-chat" | "svg-tabbar-home" | "svg-tabbar-mine">;
            default: string;
            required: true;
        };
    }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
        name: {
            type: import("vue").PropType<"svg-bangbangtang" | "svg-baomihua" | "svg-bingqilin" | "svg-hanbao" | "svg-pintu" | "svg-react" | "svg-sanmingzhi" | "svg-sharp-arrow-back-ios" | "svg-sharp-check" | "svg-tabbar-chat" | "svg-tabbar-home" | "svg-tabbar-mine">;
            default: string;
            required: true;
        };
    }>>, {
        name: "svg-bangbangtang" | "svg-baomihua" | "svg-bingqilin" | "svg-hanbao" | "svg-pintu" | "svg-react" | "svg-sanmingzhi" | "svg-sharp-arrow-back-ios" | "svg-sharp-check" | "svg-tabbar-chat" | "svg-tabbar-home" | "svg-tabbar-mine";
    }>;
  }
}
